## This File Should Be Here For MacOS: /Users/Shared/gitlab-runner/config
## This Is here to show example
concurrent = 1

[[runners]]
  name = "neptune"
  url = "http://gitlab.jupiter.com"
  token = "glrt-nQWdehPiBUHqtw_hgWwF"
  executor = "docker"
    [runners.docker]
    image = "alpine:latest" # default Docker image to use
    privileged = false # set to true if you need privileged access
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    shm_size = 0